//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonents_equipment
    {
        public int id_equipment { get; set; }
        public string name { get; set; }
        public int count_portov { get; set; }
        public string standart_transmission { get; set; }
        public double speed_transmission { get; set; }
        public Nullable<int> id_abonent { get; set; }
    
        public virtual Abonents Abonents { get; set; }
    }
}
