//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int id_application { get; set; }
        public int id_abonent { get; set; }
        public int id_name_service { get; set; }
        public System.DateTime date_create { get; set; }
        public string status { get; set; }
        public string type_problem { get; set; }
        public string opisanie { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<int> id_staff { get; set; }
    
        public virtual Abonents Abonents { get; set; }
        public virtual name_service name_service { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
