//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int id_service { get; set; }
        public int id_abonent { get; set; }
        public int id_name_service { get; set; }
    
        public virtual Abonents Abonents { get; set; }
        public virtual name_service name_service { get; set; }
    }
}
